### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by rapgro** [micha/json-table#10]
Hi, 
thanks for this nice util.
FYI I've built a package in the official Fedora repository. Currently, rawhide only is supported, maybe I can build later for more branches, e.g. EPEL, too.
Regards.

**Comment by johnkerl** [comment]
@rapgro awesome!! Are you aware of https://apps.fedoraproject.org/packages/miller by @skitt?

**Comment by micha** [comment]
Thank you! (Sorry for very late reply.) I'll close this issue for now but please feel free to reopen if you like.
