### ISSUE TITLE
How do I convert a JSON file to HTML wholesale?

### ISSUE THREAD

**Issue by arisboch** [micha/json-table#12]
The whole file, no selection of any parts of it.

**Comment by MarjaE2** [comment]
I'm trying to convert to csv, but running into the same problem.

jt -c input.dat output.csv doesn't seem to do anythng. I've looked over the examples, but can't begin to find my way around them...

**Comment by micha** [comment]
@arisboch What do you mean by "convert JSON file to HTML"? Can you provide an example of a small JSON file and the desired HTML result?

@MarjaE2 What did you want it to do, exactly? Please provide an example of input and result.

**Comment by micha** [comment]
Since this issue is pretty old I assume the question has long since been either answered or another solution has been found. Feel free to reopen this issue if you like.

**Comment by MarjaE2** [comment]
I want to convert a book list formatted as json to csv so I could import it into Calibre. I don't have a result to share, though.
