### ISSUE TITLE
Converting large JSON data

### ISSUE THREAD

**Issue by dwiehoff** [micha/json-table#13]
I have a 9 MB large json file. When pasting the content, it takes a long time for the terminal to react again. Running the command leads to `zsh: parse error`:

```
jt messages [ type % ] [ user % ] [ ts % ] [ text % ] thread_replies [ user % ] [ text % ] -c <<EOT
heredoc> >....

              "ts": 1644731555.151159
            }
          ],
          "parent_user_id": "U0xxx6",
          "team": "T0xxxP",
          "replace_original": false,
          "delete_original": false,
          "blocks": [
            {
              "type": "rich_text",
              "block_id": "lXKs"
            }
          ]
        }
      ]
    }
  ],
  "channel_id": "C0xxx8"
}
EOT
zsh: parse error
```

**Comment by micha** [comment]
Have you tried piping the file to `jt` instead of using a "heredoc"? Like this:

```bash
jt -c messages [ type % ] [ user % ] [ ts % ] [ text % ] thread_replies [ user % ] [ text % ] 
 < largefile.json
```

Or, equivalently:

```bash
cat largefile.json | jt -c messages [ type % ] [ user % ] [ ts % ] [ text % ] thread_replies [ user % ] [ text % ]
```

(Also note that the `-c` option must come before any `jt` commands, as above.)

**Comment by micha** [comment]
This issue is pretty old, so I assume either the answer you were looking for has been found or you found another solution to your problem. Feel free to reopen this issue if you like.
