### ISSUE TITLE
Property name with no modifier should yield value

### ISSUE THREAD

**Issue by arichiardi** [micha/json-table#5]
This tool is very very cool (especially the language it is written in!).

I found one thing a bit counter-intuitive, in my opinion this:

```
aws cloudfront update-distribution --id XXX --generate-cli-skeleton | jt DistributionConfig CacheBehaviors Items Compress
```

Should yield the value of the key with no additional `%`.

Of course, maybe there is a very good reason not to do this, in which case, I will quite happily adapt.

Thanks a lot!

**Comment by alandipert** [comment]
Just so I understand, are you proposing that `%` should be appended automatically to path sequences that do not end in one?

I like it!  What do you think @micha?

**Comment by arichiardi** [comment]
Yes! to get values a `%` seems a bit redundant imho

**Comment by micha** [comment]
Thanks for the suggestion, how do you guys feel about that commit? Does it break anything?

**Comment by arichiardi** [comment]
Looks cool! Is it released already? Just asking, I am not on my dev machine and can't build now

**Comment by micha** [comment]
I haven't pushed a release version yet, I think I'll make some tests first!
