### ISSUE TITLE
make fails on 32-bit

### ISSUE THREAD

**Issue by pinoyyid** [micha/json-table#8]
My make is failing with ...
js.c:346:9: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘size_t’ [-Werror=format]
js.c:346:9: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘size_t’ [-Werror=format]

when run on ...
Linux p3 2.6.38.6-27.fc15.i686.PAE #1 SMP Sun May 15 17:39:47 UTC 2011 i686 i686 i386 GNU/Linux

**Comment by micha** [comment]
@pinoyyid Should be fixed now, can you test please?
