### ISSUE TITLE
Usage: display array as-is in a single cell (instead of getting unfolded into multiple rows)

### ISSUE THREAD

**Issue by shadiakiki1986** [micha/json-table#9]
Hello. Not sure where to ask *usage* questions, so I just opened this issue.
After reading the man page, I'm still unclear on how I can display an array in-line in a cell.
The application is to display the [json output from scrapy](https://docs.scrapy.org/en/latest/intro/tutorial.html#storing-the-scraped-data)

e.g.

```
jt [ foo % ] [ bar % ] [ baz % ]<<EOT
[
  { "foo": 1,    "bar": 2,    "baz": [3, 4]  },
  { "foo": 5,    "bar": 6,    "baz": [7, 8]  }
]
EOT
```

currently displays

```
1       2       3
1       2       4
5       6       7
5       6       8
```

but I'd like it to display

```
1       2       [3, 4]
5       6       [7, 8]
```

**Comment by mdawaffe** [comment]
If you turn [off implicit iteration with the `-a` flag](http://htmlpreview.github.io/?https://raw.githubusercontent.com/micha/json-table/master/jt.1.html#Explicit-Iteration), and specify which arrays you want to iterate over with `.`, you can get the output you're looking for (minus some whitespace differences).

```
jt -a . [ foo % ] [ bar % ] [ baz % ]<<EOT
[
  { "foo": 1,    "bar": 2,    "baz": [3, 4]  },
  { "foo": 5,    "bar": 6,    "baz": [7, 8]  }
]
EOT
```

**Comment by shadiakiki1986** [comment]
Awesome! Thanks so much

**Comment by micha** [comment]
Thanks @mdawaffe and @shadiakiki1986 !
